<?php

/**
 * BasePurchaseItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $purchase_order_id
 * @property integer $item_id
 * @property integer $nos
 * @property PurchaseOrder $PurchaseOrder
 * @property Item $Item
 * @property Doctrine_Collection $PurchaseItemsTransport
 * 
 * @method integer             getPurchaseOrderId()        Returns the current record's "purchase_order_id" value
 * @method integer             getItemId()                 Returns the current record's "item_id" value
 * @method integer             getNos()                    Returns the current record's "nos" value
 * @method PurchaseOrder       getPurchaseOrder()          Returns the current record's "PurchaseOrder" value
 * @method Item                getItem()                   Returns the current record's "Item" value
 * @method Doctrine_Collection getPurchaseItemsTransport() Returns the current record's "PurchaseItemsTransport" collection
 * @method PurchaseItems       setPurchaseOrderId()        Sets the current record's "purchase_order_id" value
 * @method PurchaseItems       setItemId()                 Sets the current record's "item_id" value
 * @method PurchaseItems       setNos()                    Sets the current record's "nos" value
 * @method PurchaseItems       setPurchaseOrder()          Sets the current record's "PurchaseOrder" value
 * @method PurchaseItems       setItem()                   Sets the current record's "Item" value
 * @method PurchaseItems       setPurchaseItemsTransport() Sets the current record's "PurchaseItemsTransport" collection
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePurchaseItems extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('purchase_items');
        $this->hasColumn('purchase_order_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nos', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PurchaseOrder', array(
             'local' => 'purchase_order_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PurchaseItemsTransport', array(
             'local' => 'id',
             'foreign' => 'purchase_item_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}