<?php

/**
 * BaseSalesPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sales_order_id
 * @property integer $payment_id
 * @property SalesOrder $SalesOrder
 * @property Payment $Payment
 * 
 * @method integer      getSalesOrderId()   Returns the current record's "sales_order_id" value
 * @method integer      getPaymentId()      Returns the current record's "payment_id" value
 * @method SalesOrder   getSalesOrder()     Returns the current record's "SalesOrder" value
 * @method Payment      getPayment()        Returns the current record's "Payment" value
 * @method SalesPayment setSalesOrderId()   Sets the current record's "sales_order_id" value
 * @method SalesPayment setPaymentId()      Sets the current record's "payment_id" value
 * @method SalesPayment setSalesOrder()     Sets the current record's "SalesOrder" value
 * @method SalesPayment setPayment()        Sets the current record's "Payment" value
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSalesPayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sales_payment');
        $this->hasColumn('sales_order_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('payment_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SalesOrder', array(
             'local' => 'sales_order_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Payment', array(
             'local' => 'payment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}