<?php

/**
 * BasePurchaseItemsTransport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $purchase_item_id
 * @property integer $transport_id
 * @property integer $nos
 * @property PurchaseItems $PurchaseItems
 * @property Transport $Transport
 * 
 * @method integer                getPurchaseItemId()   Returns the current record's "purchase_item_id" value
 * @method integer                getTransportId()      Returns the current record's "transport_id" value
 * @method integer                getNos()              Returns the current record's "nos" value
 * @method PurchaseItems          getPurchaseItems()    Returns the current record's "PurchaseItems" value
 * @method Transport              getTransport()        Returns the current record's "Transport" value
 * @method PurchaseItemsTransport setPurchaseItemId()   Sets the current record's "purchase_item_id" value
 * @method PurchaseItemsTransport setTransportId()      Sets the current record's "transport_id" value
 * @method PurchaseItemsTransport setNos()              Sets the current record's "nos" value
 * @method PurchaseItemsTransport setPurchaseItems()    Sets the current record's "PurchaseItems" value
 * @method PurchaseItemsTransport setTransport()        Sets the current record's "Transport" value
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePurchaseItemsTransport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('purchase_items_transport');
        $this->hasColumn('purchase_item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('transport_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nos', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PurchaseItems', array(
             'local' => 'purchase_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Transport', array(
             'local' => 'transport_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}