<?php

/**
 * BaseSalesItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sales_order_id
 * @property integer $item_id
 * @property integer $nos
 * @property SalesOrder $SalesOrder
 * @property Item $Item
 * @property Doctrine_Collection $SalesItemsTransport
 * 
 * @method integer             getSalesOrderId()        Returns the current record's "sales_order_id" value
 * @method integer             getItemId()              Returns the current record's "item_id" value
 * @method integer             getNos()                 Returns the current record's "nos" value
 * @method SalesOrder          getSalesOrder()          Returns the current record's "SalesOrder" value
 * @method Item                getItem()                Returns the current record's "Item" value
 * @method Doctrine_Collection getSalesItemsTransport() Returns the current record's "SalesItemsTransport" collection
 * @method SalesItems          setSalesOrderId()        Sets the current record's "sales_order_id" value
 * @method SalesItems          setItemId()              Sets the current record's "item_id" value
 * @method SalesItems          setNos()                 Sets the current record's "nos" value
 * @method SalesItems          setSalesOrder()          Sets the current record's "SalesOrder" value
 * @method SalesItems          setItem()                Sets the current record's "Item" value
 * @method SalesItems          setSalesItemsTransport() Sets the current record's "SalesItemsTransport" collection
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSalesItems extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sales_items');
        $this->hasColumn('sales_order_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nos', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SalesOrder', array(
             'local' => 'sales_order_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('SalesItemsTransport', array(
             'local' => 'id',
             'foreign' => 'sales_item_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}