<?php

/**
 * BaseChequePayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $payment_id
 * @property string $bank_name
 * @property integer $status
 * @property timestamp $date_end
 * 
 * @method integer       getPaymentId()  Returns the current record's "payment_id" value
 * @method string        getBankName()   Returns the current record's "bank_name" value
 * @method integer       getStatus()     Returns the current record's "status" value
 * @method timestamp     getDateEnd()    Returns the current record's "date_end" value
 * @method ChequePayment setPaymentId()  Sets the current record's "payment_id" value
 * @method ChequePayment setBankName()   Sets the current record's "bank_name" value
 * @method ChequePayment setStatus()     Sets the current record's "status" value
 * @method ChequePayment setDateEnd()    Sets the current record's "date_end" value
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChequePayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cheque_payment');
        $this->hasColumn('payment_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('bank_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}