<?php

/**
 * BaseSeller
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $address
 * @property integer $tp_hp
 * @property integer $tp_home
 * @property string $notes
 * @property Doctrine_Collection $PurchaseOrder
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getAddress()       Returns the current record's "address" value
 * @method integer             getTpHp()          Returns the current record's "tp_hp" value
 * @method integer             getTpHome()        Returns the current record's "tp_home" value
 * @method string              getNotes()         Returns the current record's "notes" value
 * @method Doctrine_Collection getPurchaseOrder() Returns the current record's "PurchaseOrder" collection
 * @method Seller              setName()          Sets the current record's "name" value
 * @method Seller              setAddress()       Sets the current record's "address" value
 * @method Seller              setTpHp()          Sets the current record's "tp_hp" value
 * @method Seller              setTpHome()        Sets the current record's "tp_home" value
 * @method Seller              setNotes()         Sets the current record's "notes" value
 * @method Seller              setPurchaseOrder() Sets the current record's "PurchaseOrder" collection
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeller extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seller');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tp_hp', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tp_home', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('notes', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PurchaseOrder', array(
             'local' => 'id',
             'foreign' => 'seller_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}