<?php

/**
 * BaseTransport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $transporter_name
 * @property timestamp $date_begin
 * @property timestamp $date_end
 * @property Doctrine_Collection $PurchaseItemsTransport
 * @property Doctrine_Collection $SalesItemsTransport
 * @property Doctrine_Collection $TransportPayment
 * 
 * @method integer             getTransporterName()        Returns the current record's "transporter_name" value
 * @method timestamp           getDateBegin()              Returns the current record's "date_begin" value
 * @method timestamp           getDateEnd()                Returns the current record's "date_end" value
 * @method Doctrine_Collection getPurchaseItemsTransport() Returns the current record's "PurchaseItemsTransport" collection
 * @method Doctrine_Collection getSalesItemsTransport()    Returns the current record's "SalesItemsTransport" collection
 * @method Doctrine_Collection getTransportPayment()       Returns the current record's "TransportPayment" collection
 * @method Transport           setTransporterName()        Sets the current record's "transporter_name" value
 * @method Transport           setDateBegin()              Sets the current record's "date_begin" value
 * @method Transport           setDateEnd()                Sets the current record's "date_end" value
 * @method Transport           setPurchaseItemsTransport() Sets the current record's "PurchaseItemsTransport" collection
 * @method Transport           setSalesItemsTransport()    Sets the current record's "SalesItemsTransport" collection
 * @method Transport           setTransportPayment()       Sets the current record's "TransportPayment" collection
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTransport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('transport');
        $this->hasColumn('transporter_name', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date_begin', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PurchaseItemsTransport', array(
             'local' => 'id',
             'foreign' => 'transport_id'));

        $this->hasMany('SalesItemsTransport', array(
             'local' => 'id',
             'foreign' => 'transport_id'));

        $this->hasMany('TransportPayment', array(
             'local' => 'id',
             'foreign' => 'transport_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}