<?php

/**
 * BasePurchasePayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $purchase_order_id
 * @property integer $payment_id
 * @property PurchaseOrder $PurchaseOrder
 * @property Payment $Payment
 * 
 * @method integer         getPurchaseOrderId()   Returns the current record's "purchase_order_id" value
 * @method integer         getPaymentId()         Returns the current record's "payment_id" value
 * @method PurchaseOrder   getPurchaseOrder()     Returns the current record's "PurchaseOrder" value
 * @method Payment         getPayment()           Returns the current record's "Payment" value
 * @method PurchasePayment setPurchaseOrderId()   Sets the current record's "purchase_order_id" value
 * @method PurchasePayment setPaymentId()         Sets the current record's "payment_id" value
 * @method PurchasePayment setPurchaseOrder()     Sets the current record's "PurchaseOrder" value
 * @method PurchasePayment setPayment()           Sets the current record's "Payment" value
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePurchasePayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('purchase_payment');
        $this->hasColumn('purchase_order_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('payment_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PurchaseOrder', array(
             'local' => 'purchase_order_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Payment', array(
             'local' => 'payment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}