<?php

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property float $sales_unit_price
 * @property float $purchase_unit_price
 * @property string $description
 * @property integer $stock_available
 * @property Doctrine_Collection $PurchaseItems
 * @property Doctrine_Collection $SalesItems
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method float               getSalesUnitPrice()      Returns the current record's "sales_unit_price" value
 * @method float               getPurchaseUnitPrice()   Returns the current record's "purchase_unit_price" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method integer             getStockAvailable()      Returns the current record's "stock_available" value
 * @method Doctrine_Collection getPurchaseItems()       Returns the current record's "PurchaseItems" collection
 * @method Doctrine_Collection getSalesItems()          Returns the current record's "SalesItems" collection
 * @method Item                setName()                Sets the current record's "name" value
 * @method Item                setSalesUnitPrice()      Sets the current record's "sales_unit_price" value
 * @method Item                setPurchaseUnitPrice()   Sets the current record's "purchase_unit_price" value
 * @method Item                setDescription()         Sets the current record's "description" value
 * @method Item                setStockAvailable()      Sets the current record's "stock_available" value
 * @method Item                setPurchaseItems()       Sets the current record's "PurchaseItems" collection
 * @method Item                setSalesItems()          Sets the current record's "SalesItems" collection
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('sales_unit_price', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('purchase_unit_price', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('stock_available', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PurchaseItems', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $this->hasMany('SalesItems', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}