<?php

/**
 * BasePayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property float $amount
 * @property timestamp $date
 * @property integer $type
 * @property Doctrine_Collection $PurchasePayment
 * @property Doctrine_Collection $TransportPayment
 * @property Doctrine_Collection $SalesPayment
 * 
 * @method float               getAmount()           Returns the current record's "amount" value
 * @method timestamp           getDate()             Returns the current record's "date" value
 * @method integer             getType()             Returns the current record's "type" value
 * @method Doctrine_Collection getPurchasePayment()  Returns the current record's "PurchasePayment" collection
 * @method Doctrine_Collection getTransportPayment() Returns the current record's "TransportPayment" collection
 * @method Doctrine_Collection getSalesPayment()     Returns the current record's "SalesPayment" collection
 * @method Payment             setAmount()           Sets the current record's "amount" value
 * @method Payment             setDate()             Sets the current record's "date" value
 * @method Payment             setType()             Sets the current record's "type" value
 * @method Payment             setPurchasePayment()  Sets the current record's "PurchasePayment" collection
 * @method Payment             setTransportPayment() Sets the current record's "TransportPayment" collection
 * @method Payment             setSalesPayment()     Sets the current record's "SalesPayment" collection
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePayment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('payment');
        $this->hasColumn('amount', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PurchasePayment', array(
             'local' => 'id',
             'foreign' => 'payment_id'));

        $this->hasMany('TransportPayment', array(
             'local' => 'id',
             'foreign' => 'payment_id'));

        $this->hasMany('SalesPayment', array(
             'local' => 'id',
             'foreign' => 'payment_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}