<?php

/**
 * PurchasePaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PurchasePaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PurchasePaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PurchasePayment');
    }
}