<?php

/**
 * SalesItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalesItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalesItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalesItems');
    }
}