<?php

/**
 * SalesPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalesPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalesPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalesPayment');
    }
}