<?php

/**
 * TransportPaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TransportPaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TransportPaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TransportPayment');
    }
}