<?php

/**
 * PurchaseItemsTransportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PurchaseItemsTransportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PurchaseItemsTransportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PurchaseItemsTransport');
    }
}