<?php

/**
 * PurchaseItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PurchaseItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PurchaseItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PurchaseItems');
    }
}