<?php

/**
 * SalesItemsTransportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalesItemsTransportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalesItemsTransportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalesItemsTransport');
    }
}