<?php

/**
 * SalesItems
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    open-stock-management
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SalesItems extends BaseSalesItems
{
}
