# config/doctrine/schema.yml
Seller:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }
    address: { type: string(255) }
    tp_hp: { type: integer }
    tp_home: { type: integer }
    notes: { type: string(255) }

Client:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }
    address: { type: string(255) }
    tp_hp: {type: integer }
    tp_home: { type: integer }
    notes: { type: string(255) }

PurchaseOrder:
  actAs: { Timestampable: ~ }
  columns:
    seller_id: { type: integer, notnull: true }
    date_begin: { type: timestamp, notnull: true }
    date_end: { type: timestamp }
    total_price: { type: float }
    total_paid: { type: float }
    total_due: { type: float }
    order_status: { type: integer }
    notes: { type: string(255) }
  relations:
    Seller: { onDelete: CASCADE, local: seller_id, foreign: id }

SalesOrder:
  actAs: { Timestampable: ~ }
  columns:
    client_id: { type: integer, notnull: true }
    date_begin: { type: timestamp, notnull: true }
    date_end: { type: timestamp }
    total_price: { type: float }
    total_paid: { type: float }
    total_due: { type: float }
    order_status: { type: integer}
    notes: { type: string(255) }
  relations:
    Client: { onDelete: CASCADE, local: client_id, foreign: id }

Item:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255) ,unique: true }
    sales_unit_price: { type: float }
    purchase_unit_price: { type: float }
    description: { type: string(255) }
    stock_available: { type: integer}

PurchaseItems:
  actAs: { Timestampable: ~ }
  columns:
    purchase_order_id: { type: integer }
    item_id: { type: integer }
    nos: { type: integer }
  relations:
    PurchaseOrder:  { onDelete: CASCADE, local: purchase_order_id , foreign: id }
    Item: { onDelete: CASCADE, local: item_id, foreign: id }

SalesItems:
  actAs: { Timestampable: ~ }
  columns:
    sales_order_id: { type: integer, notnull: true }
    item_id: { type: integer, notnull: true }
    nos: { type: integer }
  relations:
    SalesOrder: { onDelete: CASCADE, local: sales_order_id , foreign: id }
    Item: { onDelete: CASCADE, local: item_id, foreign: id }

Transport:
  actAs: { Timestampable: ~ }
  columns:
    transporter_name: { type: integer, notnull: true }
    date_begin: { type: timestamp }
    date_end: { type: timestamp }

PurchaseItemsTransport :
  columns:
    purchase_item_id: { type: integer, notnull: true }
    transport_id: { type: integer, notnull: true }
    nos: { type: integer }
  relations:
    PurchaseItems:  { onDelete: CASCADE, local: purchase_item_id  , foreign: id }
    Transport: { onDelete: CASCADE, local: transport_id, foreign: id }


SalesItemsTransport :
  columns:
    sales_item_id: {type: integer, notnull: true }
    transport_id: { type: integer, notnull: true }
    nos: { type: integer }
  relations:
    SalesItems: { onDelete: CASCADE, local: sales_item_id  , foreign: id }
    Transport:  { onDelete: CASCADE, local: transport_id, foreign: id }

PurchasePayment :
  columns:
    purchase_order_id: { type: integer, notnull: true }
    payment_id: { type: integer, notnull: true }
  relations:
    PurchaseOrder: { onDelete: CASCADE, local: purchase_order_id  , foreign: id }
    Payment:  { onDelete: CASCADE, local: payment_id, foreign: id }

TransportPayment :
  columns:
    transport_id: { type: integer, notnull: true }
    payment_id: { type: integer, notnull: true }
  relations:
    Transport: { onDelete: CASCADE, local: transport_id  , foreign: id }
    Payment:  { onDelete: CASCADE, local: payment_id, foreign: id }

SalesPayment:
  columns:
    sales_order_id: { type: integer, notnull: true }
    payment_id: { type: integer, notnull: true }
  relations:
    SalesOrder: { onDelete: CASCADE, local: sales_order_id  , foreign: id }
    Payment:  { onDelete: CASCADE, local: payment_id, foreign: id }

ChequePayment:
  columns:
    payment_id: { type: integer, notnull: true }
    bank_name : { type: string(255) }
    status : { type: integer }
    date_end : { type: timestamp }

Payment:
  actAs: { Timestampable: ~ }
  columns:
    amount: { type: float }
    date: { type: timestamp }
    type: { type: integer }
